### PR TITLE
Added Online command (see description)

### PR DESCRIPTION
**Pull request by QuartzWarrior**
I will add a "how long was the player online" command soon!
```
import hypixelaPY import Hypixel
hypixel = await Hypixel("API key")
player = await hypixel.player.get(name="Dream")
if player.logins.online is True:
	print(f"{player.name} is currently online.")
else:
	print(f"{player.name} is currently offline.")
```

### CODE REVIEW

**Comment by ernieIzde8ski** [comment]
Bro what linter do you use

**Comment by armenium** [comment]
@ernieIzde8ski I am big fan of your work, Maker of rat

**Comment by QuartzWarrior** [comment]
> Bro what linter do you use

None, I just test it out to make sure it works

**Comment by armenium** [comment]
> > Bro what linter do you use
> 
> None, I just test it out to make sure it works

I salute you, Dear Person

**Comment by QuartzWarrior** [comment]
never gonna be pulled, gonna make a new pr

**Pull request closed without merging**
